version: "3.9"

services:
  whisper:
    image: ${WHISPER_IMAGE}
    # cannot have a `container_name` as it will be scaled
    expose:
      - "5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]



  load-balancer:
    image: nginx:latest
    container_name: nginx-whisper
    volumes:
      # config needs to define the number of whisper services in `upstream`
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/app/data/
    depends_on:
      - whisper
    ports:
      - "80:8080"
